name: Build and Publish NPM Package

on:
  release:
    types: [published]

env:
  NODE_VERSION: ">=20.15.0"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"

      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'

      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun install
        run: |
          bun install --frozen-lockfile
      - name: Lint
        run: bun lint
      - name: Build
        run: bun run build
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: "https://registry.npmjs.org"
          cache: yarn
      - name: Publish
        run: yarn publish --access public --non-interactive --new-version ${{ steps.version.outputs.value }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
